eventtype_upload_codes = {
    'CIC': {
        '_tablename': 'events',
        '_blobs': ['TR'],
        '_has_ext_time': True,
        'RED': 'data_reduction',
        'EVENTRATE': 'event_rate',
        'TRIGPATTERN': 'trigger_pattern',
        'BL': 'baseline',
        'STDDEV': 'std_dev',
        'NP': 'n_peaks',
        'PH': 'pulseheights',
        'IN': 'integrals',
        'TR': 'traces',
    },
    'ERR': {
        '_tablename': 'errors',
        '_blobs': ['ERRMSG'],
        '_has_ext_time': False,
        'ERRMSG': 'messages',
    },
    'CMP': {
        '_tablename': 'comparator',
        '_blobs': [],
        '_has_ext_time': True,
        'CMP_DEVICE': 'device',
        'CMP_COMPARATOR': 'comparator',
        'CMP_COUNT': 'count',
    },
}
