"""
Definities van alle vaste waarden in de database.
"""

# sensorinfotype id's
SENSORINFOTYPE_STARTDAT     = 1
SENSORINFOTYPE_EINDDAT      = 2
SENSORINFOTYPE_STAT         = 3
SENSORINFOTYPE_LONG         = 4
SENSORINFOTYPE_LAT          = 5
SENSORINFOTYPE_PASS         = 6
SENSORINFOTYPE_UPLERRORCODE = 7
SENSORINFOTYPE_UPLERRORMSG  = 8
SENSORINFOTYPE_X            = 9
SENSORINFOTYPE_Y            = 10
SENSORINFOTYPE_Z            = 11
SENSORINFOTYPE_SCINT1NORTH  = 12
SENSORINFOTYPE_SCINT1EAST   = 13
SENSORINFOTYPE_SCINT1UP     = 14
SENSORINFOTYPE_SCINT2NORTH  = 15
SENSORINFOTYPE_SCINT2EAST   = 16
SENSORINFOTYPE_SCINT2UP     = 17
SENSORINFOTYPE_SCINT3NORTH  = 18
SENSORINFOTYPE_SCINT3EAST   = 19
SENSORINFOTYPE_SCINT3UP     = 20
SENSORINFOTYPE_SCINT4NORTH  = 21
SENSORINFOTYPE_SCINT4EAST   = 22
SENSORINFOTYPE_SCINT4UP     = 23

# eventtypes
EVENTTYPE_COINCIDENCE = 1
EVENTTYPE_ADCSETTINGS = 2
EVENTTYPE_GPS         = 3

# eventdatatypes
EVENTDATATYPE_E_SOFTWAREVERSION  = 1
EVENTDATATYPE_E_GPSEVENTNUM      = 2
EVENTDATATYPE_E_ADCEVENTNUM      = 3
EVENTDATATYPE_E_GPSSTATUS        = 4
EVENTDATATYPE_E_SOFTWAREDEADTIME = 5
EVENTDATATYPE_E_TRACE1           = 6
EVENTDATATYPE_E_TRACE2           = 7
EVENTDATATYPE_E_TRACE3           = 8
EVENTDATATYPE_E_TRACE4           = 9
EVENTDATATYPE_E_GPSREADOUTDELAY  = 10

EVENTDATATYPE_A_SOFTWAREVERSION   = 11
EVENTDATATYPE_A_ADCCOUNTMIN1      = 12
EVENTDATATYPE_A_ADCCOUNTMAX1      = 13
EVENTDATATYPE_A_ADCCOUNTZEROVOLT1 = 14
EVENTDATATYPE_A_ADCVOLTPERCOUNT1  = 15
EVENTDATATYPE_A_ADCCOUNTMIN2      = 16
EVENTDATATYPE_A_ADCCOUNTMAX2      = 17
EVENTDATATYPE_A_ADCCOUNTZEROVOLT2 = 18
EVENTDATATYPE_A_ADCVOLTPERCOUNT2  = 19
EVENTDATATYPE_A_TIMEMIN1          = 20
EVENTDATATYPE_A_TIMEMAX1          = 21
EVENTDATATYPE_A_NSAMPLES1         = 22
EVENTDATATYPE_A_TIMEMIN2          = 23
EVENTDATATYPE_A_TIMEMAX2          = 24
EVENTDATATYPE_A_NSAMPLES2         = 25

EVENTDATATYPE_G_SOFTWAREVERSION    = 26
EVENTDATATYPE_G_GPSLAT             = 27
EVENTDATATYPE_G_GPSLONG            = 28
EVENTDATATYPE_G_GPSHEIGHT          = 29
EVENTDATATYPE_G_GPSSTATUS          = 30
EVENTDATATYPE_G_GPSEVENTNUM        = 31
EVENTDATATYPE_G_SATELLITENUMBERS   = 32
EVENTDATATYPE_G_SATELLITESTRENGTHS = 33

# eventwarehouse.event
EVENT_E_EVENT_ID     = 0
EVENT_E_SENSOR_ID    = 1
EVENT_E_EVENTTYPE_ID = 2
EVENT_E_DATE         = 3
EVENT_E_TIME         = 4
EVENT_E_NANOSECS     = 5

EVENT_C_SOFTWAREVERSION  = 6
EVENT_C_GPSEVENTNUM      = 7
EVENT_C_ADCEVENTNUM      = 8
EVENT_C_GPSSTATUS        = 9
EVENT_C_SOFTWAREDEADTIME = 10
EVENT_C_TRACE1           = 11
EVENT_C_TRACE2           = 12
EVENT_C_TRACE3           = 13
EVENT_C_TRACE4           = 14
EVENT_C_GPSREADOUTDELAY  = 15

EVENT_A_SOFTWAREVERSION   = 16
EVENT_A_ADCCOUNTMIN1      = 17
EVENT_A_ADCCOUNTMAX1      = 18
EVENT_A_ADCCOUNTZEROVOLT1 = 19
EVENT_A_ADCVOLTPERCOUNT1  = 20
EVENT_A_ADCCOUNTMIN2      = 21
EVENT_A_ADCCOUNTMAX2      = 22
EVENT_A_ADCCOUNTZEROVOLT2 = 23
EVENT_A_ADCVOLTPERCOUNT2  = 24
EVENT_A_TIMEMIN1          = 25
EVENT_A_TIMEMAX1          = 26
EVENT_A_NSAMPLES1         = 27
EVENT_A_TIMEMIN2          = 28
EVENT_A_TIMEMAX2          = 29
EVENT_A_NSAMPLES2         = 30

EVENT_G_SOFTWAREVERSION    = 31
EVENT_G_GPSLAT             = 32
EVENT_G_GPSLONG            = 33
EVENT_G_GPSHEIGHT          = 34
EVENT_G_GPSSTATUS          = 35
EVENT_G_GPSEVENTNUM        = 36
EVENT_G_SATELLITENUMBERS   = 37
EVENT_G_SATELLITESTRENGTHS = 38
