[tool.ruff]
line-length = 120
target-version = 'py310'
extend-exclude = [
    'doc/',
    'examples/',
    'migration/',
    'scripts/',
]

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
select = ['ALL']  # https://docs.astral.sh/ruff/rules/
ignore = [
    'ANN',  # Type annotations not enforced
    'C901',  # Allow complex functions
    'D',  # Ignore docstring checks
    'G004',  # Allow f-string in logging
    'INP001',  # Allow scripts in implicit namespaces
    'PERF203',  # Allow try-except in loop
    'PLR0912',  # Allow functions with many branches
    'PT',  # Not using pytest
    'RET',  # Allow elif/else after return
    'S101',  # Assert is used to prevent incorrect
    'S105',  # Some hardcoded test passwords
    'S301',  # Allow usage of pickle
    'S324',  # Allow usage of md5
    'SIM108',  # No need for ternary operator
    'SLF001',  # Allow using private members
    'TRY400',  # Allow logging.error instead of logging.exception

    # TODO: Consider improvements so these are no longer needed
    'B018',  # Checking if global is defined
    'PLW0603',  # Using globals for config and station_list
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.lint.isort]
lines-between-types = 1
section-order = [
    'future',
    'standard-library',
    'third-party',
    'first-party',
    'local-folder',
]

[tool.coverage.run]
branch = true
source = [
    'tests',
    'writer',
    'wsgi',
]

[tool.coverage.report]
show_missing = true
skip_empty = true
skip_covered = true
